<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<SboxInstallDir Condition="'$(SboxInstallDir)' == ''">$(MSBuildProgramFiles32)/Steam/steamapps/common/sbox</SboxInstallDir>
		<SboxManagedPath Condition="'$(SboxManagedPath)' == ''">$(SboxInstallDir)/bin/managed</SboxManagedPath>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>doom_port</AssemblyName>
		<PackageId>doom_port</PackageId>
		<LangVersion>14</LangVersion>
		<NoWarn>1701;1702;1591;</NoWarn>
		<WarningsAsErrors></WarningsAsErrors>
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<DefineConstants>SANDBOX</DefineConstants>
		<AllowUnsafeBlocks>False</AllowUnsafeBlocks>
		<OutputPath>bin/$(Configuration)/</OutputPath>
		<DocumentationFile>$(OutputPath)doom_port.xml</DocumentationFile>
		<RootNamespace>Sandbox</RootNamespace>
		<Nullable>disable</Nullable>
		<DefaultItemExcludes>$(DefaultItemExcludes);**/editor/**;**/unittest/**</DefaultItemExcludes>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="Sandbox.Internal.GlobalGameNamespace" Static="true" />
		<Using Include="Microsoft.AspNetCore.Components" />
		<Using Include="Microsoft.AspNetCore.Components.Rendering" />
	</ItemGroup>

	<ItemGroup>
		<Analyzer Include="$(SboxManagedPath)/Sandbox.CodeUpgrader.dll" Condition="Exists('$(SboxManagedPath)/Sandbox.CodeUpgrader.dll')"/>
		<Analyzer Include="$(SboxManagedPath)/Sandbox.Generator.dll"/>
		<Reference Include="$(SboxManagedPath)/Sandbox.System.dll"/>
		<Reference Include="$(SboxManagedPath)/Sandbox.Engine.dll"/>
		<Reference Include="$(SboxManagedPath)/Sandbox.Filesystem.dll"/>
		<Reference Include="$(SboxManagedPath)/Sandbox.Reflection.dll"/>
		<Reference Include="$(SboxManagedPath)/Sandbox.Mounting.dll"/>
		<Reference Include="$(SboxManagedPath)/Microsoft.AspNetCore.Components.dll"/>
	</ItemGroup>

</Project>
