#!/usr/bin/env python3
"""Reproduce isolated Heretic C# definitions from the pinned GPL source checkout.
Usage: python tools/import_heretic_definitions.py /path/to/chocolate-doom [--check]
No network, C execution, or unrestricted expression evaluation is performed.
"""
# Copyright (C) 2026 s&Doom contributors; SPDX-License-Identifier: GPL-2.0-or-later
import argparse
import ast
import hashlib
from pathlib import Path
import re

REVISION = '895f581c5d91497bdda0516612da803fe5843e28'
HASHES = {
    'info.c': '7f745dd2999d739cf5a99954cac0af74af00209c37ae5e825ffbfc4c33534969',
    'info.h': '55efe6480d8e76b1481b4e169c6291d6f50984d68d606baaf2cbade248d86e5f',
    'doomdef.h': 'e6329f19cc65cb906be03c8935d61b69b771bd7e51d3ee58c52c640a96e2afe2',
    'sounds.h': 'eefaabc67de7cdd184106fbab80f8c1bec7cc6842bd6325f0d8022bcd031f1ea',
    'p_pspr.c': '63f87080fddf04f4258f137edcc64c6fafebd7f0201f0a647c565a380c2b5bfb',
    'p_local.h': 'd2b4d753a82c57a77a1aeb27aa6b87ede178d2cea79a8d941819c771c384288c',
}

def clean(s):
    return re.sub(r'/\*.*?\*/|//[^\n]*', '', s, flags=re.S)

def enum_names(s, kind):
    for body, name in re.findall(r'typedef\s+enum\s*\{(.*?)\}\s*(\w+)\s*;', clean(s), re.S):
        if name == kind:
            names = [x.strip() for x in body.split(',') if x.strip()]
            if not all(re.fullmatch(r'\w+', n) for n in names):
                raise ValueError('Explicit enum values need review: ' + kind)
            return names
    raise ValueError('Missing enum ' + kind)

def array(s, name):
    m = re.search(r'\b' + name + r'\s*\[[^\]]*\]\s*=\s*\{(.*?)\n\};', s, re.S)
    if not m:
        raise ValueError('Missing array ' + name)
    return m[1]

def fields(s):
    return [v.strip() for v in clean(s).split(',') if v.strip()]

def generate(source):
    symbols = {'FRACUNIT': 65536}
    def number(expr):
        def visit(n):
            if isinstance(n, ast.Constant) and type(n.value) is int: return n.value
            if isinstance(n, ast.Name): return symbols[n.id]
            if isinstance(n, ast.UnaryOp) and isinstance(n.op, ast.USub): return -visit(n.operand)
            if isinstance(n, ast.BinOp):
                a, b = visit(n.left), visit(n.right)
                if isinstance(n.op, ast.Mult): return a * b
                if isinstance(n.op, ast.BitOr): return a | b
                if isinstance(n.op, ast.Add): return a + b
                if isinstance(n.op, ast.LShift): return a << b
            raise ValueError('Unsupported expression: ' + expr)
        return visit(ast.parse(expr.strip(), mode='eval').body)
    enum_specs = [
        ('HereticSpriteId','info.h','spritenum_t'),
        ('HereticStateId','info.h','statenum_t'),
        ('HereticActorType','info.h','mobjtype_t'),
        ('HereticSoundId','sounds.h','sfxenum_t'),
        ('HereticWeapon','doomdef.h','weapontype_t'),
        ('HereticAmmo','doomdef.h','ammotype_t'),
    ]
    enums = {}
    for target, file, kind in enum_specs:
        names = enum_names(source[file],kind)
        enums[target] = names
        symbols.update({name:i for i,name in enumerate(names)})
    flag_groups = {'HereticActorFlags': [], 'HereticActorFlags2': []}
    for name, expr in re.findall(r'^#define\s+((?:MF_|MF2_|USE_|AMMO_)[A-Z0-9_]+)\s+([^\n]+)', clean(source['doomdef.h'] + '\n' + source['p_local.h']), re.M):
        symbols[name] = number(expr)
        if name.startswith('MF2_'): flag_groups['HereticActorFlags2'].append((name, symbols[name]))
        elif name.startswith('MF_') and name != 'MF_TRANSSHIFT': flag_groups['HereticActorFlags'].append((name, symbols[name]))
    state_rows = re.findall(r'\{([^{}]+)\},?\s*//\s*(S_\w+)', array(source['info.c'],'states'))
    if [name for _,name in state_rows] != enums['HereticStateId'][:-1]:
        raise ValueError('State enum/table order mismatch')
    actions = sorted({fields(row)[3] for row,_ in state_rows} - {'NULL'})
    enums['HereticAction'] = ['None'] + actions
    actor_rows = re.findall(r'\{\s*//\s*(MT_\w+)\s*\n(.*?)\}', array(source['info.c'],'mobjinfo'), re.S)
    if [name for name,_ in actor_rows] != enums['HereticActorType'][:-1]:
        raise ValueError('Actor enum/table order mismatch')
    header = source['info.c'].split('#include')[0]
    out = [header, '// Adapted 2026-09-18: family-owned, immutable C# definitions.\n',
           '// Generated by tools/import_heretic_definitions.py; do not edit by hand.\n',
           '// Chocolate Doom ' + REVISION + ': info.c/h, doomdef.h, sounds.h, p_pspr.c, p_local.h.\n',
           'using System;\nusing System.Collections.Generic;\nnamespace ManagedDoom\n{\n']
    for name,names in enums.items():
        out.append('    public enum ' + name + '\n    {\n' + ''.join('        ' + n + ',\n' for n in names) + '    }\n')
    for name,entries in flag_groups.items():
        out.append('    [Flags] public enum ' + name + ' : uint\n    {\n        None = 0,\n' + ''.join(f'        {n} = 0x{v:08x},\n' for n,v in entries) + '    }\n')
    out += ['''    public readonly record struct HereticStateDefinition(HereticSpriteId Sprite, int Frame, int Tics, HereticAction Action, HereticStateId Next, int Misc1, int Misc2);
    public readonly record struct HereticActorDefinition(int MapNumber, HereticStateId SpawnState, int SpawnHealth, HereticStateId SeeState, HereticSoundId SeeSound, int ReactionTime, HereticSoundId AttackSound, HereticStateId PainState, int PainChance, HereticSoundId PainSound, HereticStateId MeleeState, HereticStateId MissileState, HereticStateId CrashState, HereticStateId DeathState, HereticStateId ExtremeDeathState, HereticSoundId DeathSound, int Speed, Fixed Radius, Fixed Height, int Mass, int Damage, HereticSoundId ActiveSound, HereticActorFlags Flags, HereticActorFlags2 Flags2);
    public readonly record struct HereticWeaponDefinition(HereticAmmo Ammo, HereticStateId Up, HereticStateId Down, HereticStateId Ready, HereticStateId Attack, HereticStateId HoldAttack, HereticStateId Flash, int AmmoPerShot);
    public static class HereticDefinitions
    {
''']
    def table(name, kind, rows):
        out.append(f'        public static IReadOnlyList<{kind}> {name} {{ get; }} = Array.AsReadOnly(new {kind}[]\n        {{\n')
        out.extend('            new(' + ', '.join(values) + '), // ' + label + '\n' for label,values in rows)
        out.append('        });\n')
    states=[]
    for row,label in state_rows:
        v=fields(row)
        assert len(v)==7
        states.append((label,[f'HereticSpriteId.{v[0]}',str(number(v[1])),str(number(v[2])), 'HereticAction.' + ('None' if v[3]=='NULL' else v[3]),f'HereticStateId.{v[4]}',str(number(v[5])),str(number(v[6]))]))
    table('States','HereticStateDefinition',states)
    actors=[]
    for label,row in actor_rows:
        v=fields(row); assert len(v)==24
        converted=[]
        for i,value in enumerate(v):
            if i in (1,3,7,10,11,12,13,14): converted.append('HereticStateId.'+value if value.startswith('S_') else '(HereticStateId)'+str(number(value)))
            elif i in (4,6,9,15,21): converted.append('(HereticSoundId)'+str(number(value)))
            elif i in (17,18): converted.append('new Fixed('+str(number(value))+')')
            elif i in (22,23): converted.append('(HereticActorFlags'+('2' if i==23 else '')+')'+str(number(value))+'u')
            else: converted.append(str(number(value)))
        actors.append((label,converted))
    table('Actors','HereticActorDefinition',actors)
    for level in (1,2):
        rows=re.findall(r'\{([^{}]+)\}',array(source['p_pspr.c'],f'wpnlev{level}info'),re.S)
        ammo=fields(array(source['p_pspr.c'],f'WeaponAmmoUsePL{level}'))
        assert len(rows)==len(ammo)==9
        weapons=[]
        for i,row in enumerate(rows):
            v=fields(row); assert len(v)==7
            weapons.append((enums['HereticWeapon'][i], ['HereticAmmo.'+v[0]]+['HereticStateId.'+x for x in v[1:]]+[str(number(ammo[i]))]))
        table('Weapons'+str(level),'HereticWeaponDefinition',weapons)
    out.append('    }\n}\n')
    return ''.join(out)

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('checkout',type=Path)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    source={}
    for name,expected in HASHES.items():
        data=(args.checkout/'src/heretic'/name).read_bytes().replace(b'\r\n',b'\n')
        if hashlib.sha256(data).hexdigest()!=expected: raise ValueError('Pinned source hash mismatch: '+name)
        source[name]=data.decode()
    generated=generate(source)
    target=Path(__file__).resolve().parent.parent/'Code/ManagedDoom/Doom/Game/HereticDefinitions.Tables.cs'
    if args.check:
        if target.read_text(encoding='utf-8')!=generated: raise ValueError('Generated definitions differ; regenerate and review')
        print('PASS: Heretic definitions reproduce all pinned state, actor and weapon tables')
    else:
        target.write_text(generated,encoding='utf-8',newline='\n')
        print('Generated '+str(target))
if __name__=='__main__': main()
